name: Build SLAM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore SLAM.sln

    - name: Build solution
      run: msbuild SLAM.sln /p:Configuration=Release

    - name: Find built executable
      id: find_exe
      shell: pwsh
      run: |
        Write-Host "Searching for EXE files..."
        $exes = Get-ChildItem -Path . -Recurse -Filter *.exe
        $exes | ForEach-Object { Write-Host "Found: $($_.FullName)" }

        $exe = $exes | Where-Object { $_.FullName -match '\\bin\\Release\\.*\.exe$' } | Select-Object -First 1

        if (-not $exe) {
          Write-Error "No Release .exe found"
          exit 1
        }

        echo "exe_path=$($exe.FullName)" >> $env:GITHUB_ENV

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SLAM-executable
        path: ${{ env.exe_path }}
